import { spawn, type ChildProcessWithoutNullStreams } from 'child_process';
import type { ImageAttachment } from './types';
import type { SessionCallbacks } from './ClaudeSession';
import type { ThreadSessionOptions } from './ThreadSession';

/**
 * Thin JSON-RPC client for `codex app-server --stdio`.
 *
 * The app-server is deliberately used instead of `codex exec`: it keeps a
 * durable Codex thread open, streams item deltas, and lets Obsidian answer
 * approval requests.  The protocol is generated by the locally installed
 * Codex CLI, so payloads are kept structural here to remain compatible with
 * CLI releases without bundling a stale copy of its generated types.
 */
export class CodexSession {
  private process: ChildProcessWithoutNullStreams | null = null;
  private buffer = '';
  private nextId = 1;
  private pending = new Map<number, { resolve: (value: any) => void; reject: (error: Error) => void }>();
  private options: ThreadSessionOptions | null = null;
  private codexThreadId: string | undefined;
  private _turnInFlight = false;
  private closed = true;
  /** App-server has one active turn per thread; retain follow-ups locally. */
  private queuedTurns: Array<{ text: string; images?: ImageAttachment[] }> = [];

  constructor(private codexPath: string) {}

  get turnInFlight(): boolean { return this._turnInFlight; }
  get cwd(): string | undefined { return this.options?.cwd; }
  get hasPendingPermission(): boolean { return false; }
  canIdleReap(): boolean { return !this._turnInFlight; }

  async start(options: ThreadSessionOptions): Promise<void> {
    this.close();
    this.options = options;
    this.closed = false;
    this.process = spawn(this.codexPath, ['app-server', '--stdio'], {
      cwd: options.cwd,
      env: { ...process.env },
      stdio: 'pipe',
    });
    this.process.stdout.on('data', (chunk: Buffer) => this.consume(chunk.toString()));
    this.process.stderr.on('data', (chunk: Buffer) => console.warn('[ClaudeThreads] Codex app-server:', chunk.toString().trim()));
    this.process.on('error', (error) => this.failAll(error));
    this.process.on('exit', (code) => {
      if (!this.closed && code !== 0) this.failAll(new Error(`Codex app-server exited (${code ?? 'unknown'})`));
      this.closed = true;
    });

    await this.request('initialize', {
      clientInfo: { name: 'obsidian-claude-threads', title: 'Claude Threads', version: '0.22.1' },
      capabilities: null,
    });
    // The app-server follows the LSP-style two-phase handshake: it does not
    // accept thread requests until the client confirms initialization.
    this.notify('initialized');

    const savedCodexThread = options.resume;
    let result: any;
    if (savedCodexThread) {
      try {
        result = await this.request('thread/resume', {
          threadId: savedCodexThread,
          cwd: options.cwd,
          model: options.model ?? null,
          approvalPolicy: this.approvalPolicy(options.permissionMode),
          sandbox: 'workspace-write',
        });
      } catch (error) {
        console.warn('[ClaudeThreads] Could not resume Codex thread; starting a new one:', error);
      }
    }
    if (!result) {
      result = await this.request('thread/start', {
        cwd: options.cwd,
        model: options.model ?? null,
        approvalPolicy: this.approvalPolicy(options.permissionMode),
        sandbox: 'workspace-write',
        developerInstructions: options.appendSystemPrompt || null,
      });
    }
    this.codexThreadId = result.thread.id;
  }

  async setModel(model: string | undefined): Promise<void> {
    if (!this.codexThreadId) return;
    await this.request('thread/settings/update', { threadId: this.codexThreadId, model: model ?? null });
  }

  async setPermissionMode(mode: any): Promise<void> {
    if (!this.codexThreadId) return;
    await this.request('thread/settings/update', { threadId: this.codexThreadId, approvalPolicy: this.approvalPolicy(mode) });
  }

  send(text: string, images?: ImageAttachment[]): void {
    if (this.closed || !this.codexThreadId) throw new Error('Codex session is not running');
    if (this._turnInFlight) {
      this.queuedTurns.push({ text, images });
      return;
    }
    this.startTurn(text, images);
  }

  private startTurn(text: string, images?: ImageAttachment[]): void {
    this._turnInFlight = true;
    const input: any[] = [{ type: 'text', text, text_elements: [] }];
    for (const image of images ?? []) input.push({ type: 'image', url: `data:${image.mediaType};base64,${image.base64}` });
    this.request('turn/start', { threadId: this.codexThreadId, input })
      .catch((error) => {
        this._turnInFlight = false;
        this.options?.callbacks.onError(error instanceof Error ? error : new Error(String(error)));
      });
  }

  async interrupt(): Promise<void> {
    if (!this.codexThreadId || !this._turnInFlight) return;
    this.queuedTurns = [];
    await this.request('turn/interrupt', { threadId: this.codexThreadId });
  }

  close(): void {
    this.closed = true;
    this._turnInFlight = false;
    this.queuedTurns = [];
    this.process?.kill();
    this.process = null;
    this.failAll(new Error('Codex session closed'));
  }

  async getContextUsage(): Promise<null> { return null; }

  private approvalPolicy(mode: string | undefined): 'on-request' | 'never' {
    return mode === 'bypassPermissions' || mode === 'dontAsk' ? 'never' : 'on-request';
  }

  private request(method: string, params: Record<string, unknown>): Promise<any> {
    if (!this.process?.stdin.writable) return Promise.reject(new Error('Codex app-server is not available'));
    const id = this.nextId++;
    this.process.stdin.write(`${JSON.stringify({ method, id, params })}\n`);
    return new Promise((resolve, reject) => this.pending.set(id, { resolve, reject }));
  }

  private respond(id: number, result: Record<string, unknown>): void {
    this.process?.stdin.write(`${JSON.stringify({ id, result })}\n`);
  }

  private notify(method: string, params?: Record<string, unknown>): void {
    this.process?.stdin.write(`${JSON.stringify(params ? { method, params } : { method })}\n`);
  }

  private consume(chunk: string): void {
    this.buffer += chunk;
    let index: number;
    while ((index = this.buffer.indexOf('\n')) >= 0) {
      const line = this.buffer.slice(0, index); this.buffer = this.buffer.slice(index + 1);
      if (!line.trim()) continue;
      try { this.handle(JSON.parse(line)); } catch (error) { console.warn('[ClaudeThreads] Invalid Codex app-server message:', error); }
    }
  }

  private handle(message: any): void {
    if (typeof message.id === 'number' && ('result' in message || 'error' in message)) {
      const pending = this.pending.get(message.id); if (!pending) return;
      this.pending.delete(message.id);
      if (message.error) pending.reject(new Error(message.error.message ?? String(message.error)));
      else pending.resolve(message.result);
      return;
    }
    if (typeof message.id === 'number' && message.method) { this.handleServerRequest(message); return; }
    const callbacks = this.options?.callbacks; if (!callbacks) return;
    const params = message.params ?? {};
    switch (message.method) {
      case 'item/agentMessage/delta': callbacks.onToken(String(params.delta ?? '')); break;
      case 'item/started': {
        const item = params.item;
        if (item?.type === 'commandExecution' || item?.type === 'fileChange' || item?.type === 'mcpToolCall') {
          callbacks.onToolUse({ toolUseId: item.id, name: item.type, summary: this.toolSummary(item), status: 'pending' });
        }
        break;
      }
      case 'item/completed': {
        const item = params.item;
        if (item?.type === 'agentMessage' && item.text) callbacks.onMessage(item.text, []);
        if (item?.id && item?.type !== 'agentMessage') callbacks.onToolResult?.(item.id, item.status === 'failed' ? 'error' : 'success');
        break;
      }
      case 'turn/completed': {
        this._turnInFlight = false;
        const turn = params.turn ?? {};
        if (turn.status === 'interrupted') callbacks.onInterrupted(this.codexThreadId ?? '');
        else if (turn.status === 'failed') callbacks.onError(new Error(turn.error?.message ?? 'Codex turn failed'));
        else callbacks.onDone(this.codexThreadId ?? '', 0, 0);
        const next = this.queuedTurns.shift();
        if (next && !this.closed) this.startTurn(next.text, next.images);
        break;
      }
      case 'thread/compacted': callbacks.onCompact?.('auto', 0); break;
    }
  }

  private handleServerRequest(message: any): void {
    const callbacks = this.options?.callbacks;
    const params = message.params ?? {};
    const isApproval = /requestApproval$/.test(message.method);
    if (!callbacks || !isApproval) { this.respond(message.id, {}); return; }
    const detail = String(params.command ?? params.reason ?? 'Codex requests permission to continue');
    callbacks.onPermissionRequest('Codex', detail).then((allow) => {
      const decision = allow ? 'accept' : 'decline';
      this.respond(message.id, message.method.includes('fileChange') ? { decision } : { decision });
    }).catch(() => this.respond(message.id, { decision: 'decline' }));
  }

  private toolSummary(item: any): string {
    return String(item.command ?? item.path ?? item.server ?? item.type);
  }

  private failAll(error: Error): void {
    for (const pending of this.pending.values()) pending.reject(error);
    this.pending.clear();
  }
}
